version: '3'

services:
  app:
    container_name: github_scraper
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  redis:
    container_name: redis
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6379"
